### ISSUE TITLE
Changes to TLS secret do not get picked up automatically

### ISSUE THREAD

**Issue by easkay** [haproxytech/kubernetes-ingress#68] opened 2019-09-16 13:40 UTC
Hi folks,

Sorry if this is intended behaviour, however I noticed that the ingress controller does not seem to be watching TLS certificates configured in secrets. Thus if a certificate is renewed or replaced and the secret is recreated, the ingress controller does not reconfigure and import the new certificate.

It would be awesome if this could get sorted so that secret changes are supported. I'd be happy to provide a more ready-to-go example if you wish, including manifests.

Many thanks in advance for your assistance.

## Steps to reproduce

1. Deploy the ingress controller.
1. Deploy a sample application such as https://github.com/paulbouwer/hello-kubernetes.
1. Create a TLS certificate and key.
1. Create a Kubernetes TLS secret in the same namespace as the sample application containing the certificate.
1. Create an ingress for the sample application that references the secret created previously.
1. Generate a new certificate and key with discernably different parameters (e.g. something in subject).
1. Update the kubernetes secret.
1. Notice the certificate served by the controller has not changed.

**Comment by oktalz** [comment] 2019-09-17 12:21
hi @easkay 
this is not intended behavior, I'll look into it.

**Comment by easkay-castlight** [comment] 2019-11-27 12:28
Any updates on this @oktalz ?

**Comment by Mo3m3n** [comment] 2019-11-27 13:11
Hi @easkay-castlight 
Fixes related to handling TLS secrets and certs were added lately to the ingress controller.
Can you try the latest image and see if you still have this issues ?
Thanks

**Comment by easkay-castlight** [comment] 2019-11-27 13:24
Hi @Mo3m3n I'll give that a go today if I can, thanks for the info.

**Comment by easkay-castlight** [comment] 2019-11-27 15:45
Hi there @Mo3m3n I have managed to test 1.2.5 and I can confirm that this issue has been fixed by the changes.

**Comment by Mo3m3n** [comment] 2019-11-27 15:47
Cool Thank you @easkay-castlight for the feedback.

**Closed** 2019-12-01 14:24 UTC
