### ISSUE TITLE
Wrong port in haproxy.cfg

### ISSUE THREAD

**Issue by pmichna** [haproxytech/kubernetes-ingress#39] opened 2019-07-17 10:02 UTC
I've followed an example setup presented in https://www.haproxy.com/blog/dissecting-the-haproxy-kubernetes-ingress-controller/. I'm using minikube:

```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

My config:
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: haproxy-controller

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: haproxy-ingress-service-account
  namespace: haproxy-controller

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: haproxy-ingress-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - nodes
  - pods
  - services
  - namespaces
  - events
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "extensions"
  resources:
  - ingresses
  - ingresses/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: haproxy-ingress-cluster-role-binding
  namespace: haproxy-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: haproxy-ingress-cluster-role
subjects:
- kind: ServiceAccount
  name: haproxy-ingress-service-account
  namespace: haproxy-controller

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-configmap
  namespace: default
data:
  servers-increment: "2"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: ingress-default-backend
  name: ingress-default-backend
  namespace: haproxy-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ingress-default-backend
  template:
    metadata:
      labels:
        run: ingress-default-backend
    spec:
      containers:
      - name: ingress-default-backend
        image: gcr.io/google_containers/defaultbackend:1.0
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: ingress-default-backend
  name: ingress-default-backend
  namespace: haproxy-controller
spec:
  selector:
    run: ingress-default-backend
  ports:
  - name: port-1
    port: 8080
    protocol: TCP
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
  namespace: haproxy-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      run: haproxy-ingress
  template:
    metadata:
      labels:
        run: haproxy-ingress
    spec:
      serviceAccountName: haproxy-ingress-service-account
      containers:
      - name: haproxy-ingress
        image: haproxytech/kubernetes-ingress:1.1.4
        args:
          # - --default-ssl-certificate=default/tls-secret
          - --configmap=default/haproxy-configmap
          - --default-backend-service=haproxy-controller/ingress-default-backend
        resources:
          requests:
            cpu: "500m"
            memory: "50Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 1042
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: stat
          containerPort: 1024
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-ingress
  namespace: haproxy-controller
spec:
  selector:
    run: haproxy-ingress
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: stat
    port: 1024
    protocol: TCP
    targetPort: 1024

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: app
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
      - name: app
        image: jmalloc/echo-server
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: app
  name: app
  annotations:
    haproxy.org/check: "enabled"
    haproxy.org/forwarded-for: "enabled"
    haproxy.org/load-balance: "roundrobin"
spec:
  selector:
    run: app
  ports:
  - name: port-1
    port: 80
    protocol: TCP
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: default
spec:
  rules:
  - host: foo.bar
    http:
      paths:
      - path: /
        backend:
          serviceName: app
          servicePort: 80
```
Let's see what's inside `haproxy.cfg`.
```shell
$ kubectl -n haproxy-controller exec haproxy-ingress-7669c9dcb6-c9f58 cat /etc/haproxy/haproxy.cfg
# [...]
backend default-app-80
  mode http
  balance roundrobin
  option forwardfor
  server SRV_YkL17 172.17.0.6:80 check weight 128
  server SRV_kIZ9P 172.17.0.7:80 check weight 128
# [...]
```

The backend servers have the wrong `80` port. Obviously HAProxy can't connect:
![image](https://user-images.githubusercontent.com/3777006/61366414-d17b1080-a889-11e9-9982-266673ff310b.png)

Why the `targetPort` from the `app` `Service` is ignored? If I change the `app` container to listen on port `80` then everything works fine. Theses are the "fixing" changes:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: app
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
      - name: app
        image: jmalloc/echo-server
        env:
          - name: PORT
            value: "80"
        ports:
        - containerPort: 80
```

However, I guess this is not a desired solution.

Am I doing something wrong?

**Comment by zhilingc** [comment] 2019-07-18 06:08
+1

the ingress controller does not route traffic to the services, rather, uses the service as a reference to route traffic directly to the pods. Even so,[ it doesn't reference the targetPort in the service but the port specified in the ingress object ](https://github.com/haproxytech/kubernetes-ingress/blob/master/controller.go#L320), which is a bit misleading.

If you set the `servicePort` in your ingress object to your pod's container port it should work.

**Comment by ernoaapa** [comment] 2019-07-29 09:53
Yes, I can confirm this problem.
You can easily re-produce this by having port 8080 in the container, but in Service use port 80. 

I believe that the problem is here https://github.com/haproxytech/kubernetes-ingress/blob/master/controller.go#L205-L219. It should use the `*endpoints.Ports` information with the endpoint IP.

Found out that if you use the port name, it creates configuration what redirects to the proper port:

#### Don't work
```yaml
apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: example-service
spec:
  selector:
    app: example-service
  ports:
  - port: 80
    targetPort: 8080

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-service
  namespace: example-service
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: example-service
          servicePort: 80
```
Redirects traffic to `podIP:80` which is invalid

#### Works!
```yaml
apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: example-service
spec:
  selector:
    app: example-service
  ports:
  - name: http
    port: 80
    targetPort: 8080

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-service
  namespace: example-service
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: example-service
          servicePort: http
```
Redirects traffic to `podIP:8080` which is correct! And now still `http://example-service` works :)

**Comment by oktalz** [comment] 2019-07-30 09:09
Hi, @zhilingc , @ernoaapa 

Yes it was misleading to expect only target port or named port.
With version v1.1.5 you can use either service or target port and controller 
will route it to target port as desired.
In case if service port is defined in path, controller will use appropriate target port
linked to it.

**Comment by oktalz** [comment] 2019-07-30 09:11
this was fixed with  06d5e2.
Also I've renamed port to better reflect what is what.

**Comment by ernoaapa** [comment] 2019-07-30 09:54
Awesome @oktalz! I'll give a test run for the v1.1.5.

**Comment by ernoaapa** [comment] 2019-07-30 10:24
Verified with v1.1.5 and this is fixed! Thank you @oktalz !

**Comment by oktalz** [comment] 2019-07-30 12:12
thx @pmichna for reporting this, your help is appreciated.

**Closed** 2019-08-06 07:32 UTC
