### ISSUE TITLE
Provide support for ingress.kubernetes.io/rewrite-target annotation

### ISSUE THREAD

**Issue by safvankothawala** [haproxytech/kubernetes-ingress#174] opened 2020-04-01 14:57 UTC
Please provide support for URL Rewriting using following annotation;
ingress.kubernetes.io/rewrite-target

For example, creating following ingress should work.

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          serviceName: test
          servicePort: 80
```

**Comment by bedis** [comment] 2020-04-04 12:51
Is this a duplicate of #94 ?

**Comment by safvankothawala** [comment] 2020-04-06 09:56
This is not a duplicate of #94 
ingress.kubernetes.io/rewrite-target annotation can be used to rewrite the incoming URI to any other URI (apart from app root).
https://kubernetes.github.io/ingress-nginx/examples/rewrite/

For example, 
http://mydomain:port/customer/get/123
can be rewriten to 
http://mydomain:port/customer/123

**Comment by viper0131** [comment] 2020-04-14 16:51
That should be possible bij #94 

path-rewrite: /customer/get/(.*) /customer/\1 I guess.

**Comment by Mo3m3n** [comment] 2020-04-14 16:53
@safvankothawala 
Thanks for the feature request.
 From `v1.4.3` you can use [path-rewrite](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/README.md#path-rewrite) to configure it as mentioned by viper0131
Le me me know if said annotation answers your requirement

**Closed** 2021-01-21 10:46 UTC
Labels: enhancement

**Comment by Frankkkkk** [comment] 2021-03-02 13:32
Hi @Mo3m3n 
I think that this issue should be reopened:

Indeed, the `rewrite-target` annotation is useful when you have things like:
```
awesome.foo.bar/ -> /
test.foo.bar/awesome -> /
```
Using `path-rewrite`, we'd have to create 2 ingress resources, whereas `rewrite-target` permits using only one.


even with this simple case which is used a lot when you have backend + frontend:
```
foo.bar/service1 -> svc1 /
foo.bar/service2 -> svc2 /
```
(which indeed works with `path-rewrite`, but IMHO is cleaner with `rewrite-target`)


I'd be happy to try and implement this if you're not against the idea

Thanks and cheers !

**Comment by Mo3m3n** [comment] 2021-03-02 15:15
@Frankkkkk  Are you specifically looking for stripping the service name  from path ?
If that's the case this would be the corresponding issue https://github.com/haproxytech/kubernetes-ingress/issues/83 ?

**Comment by Frankkkkk** [comment] 2021-03-02 17:26
Well, that was embarrassing.. Indeed, it's covered in #83.
Sorry about that !

**Comment by Mo3m3n** [comment] 2021-03-02 19:40
No problem at all.
> I'd be happy to try and implement this if you're not against the idea

That would be great !
Feel free to ping me on slack if you have questions, observations on code, etc
