### ISSUE TITLE
ERROR   global.go:244 default service: service default-local-service: no service port matching '0'

### ISSUE THREAD

**Issue by nickpapadonis** [haproxytech/kubernetes-ingress#557] opened 2023-07-23 18:48 UTC
I'm following directions at:
https://www.haproxy.com/documentation/kubernetes/latest/community/install/kubernetes/

covering v1.10

$ minikube version
minikube version: v1.31.1
commit: fd3f3801765d093a485d255043149f92ec0a695f

$ helm install haproxy-kubernetes-ingress haproxytech/kubernetes-ingress -create-namespace --namespace haproxy-controller

I inspect the logs for haproxy pods and there is an error:

2023/07/23 18:28:41 ERROR   global.go:244 default service: service default-local-service: no service port matching ‘0'

Up to that point:
2023/07/23 18:28:30 HAProxy Ingress Controller v1.10.4 960be87.dirty
2023/07/23 18:28:30 Build from: https://github.com/haproxytech/kubernetes-ingress
2023/07/23 18:28:30 Git commit date: 2023/06/19 11:12:25
2023/07/23 18:28:30 ConfigMap: haproxy-controller/haproxy-kubernetes-ingress
2023/07/23 18:28:30 Ingress class: haproxy
2023/07/23 18:28:30 Empty Ingress class: false
2023/07/23 18:28:30 Publish service: haproxy-controller/haproxy-kubernetes-ingress
2023/07/23 18:28:30 Using local backend service on port: 6061
2023/07/23 18:28:30 Default ssl certificate: haproxy-controller/haproxy-kubernetes-ingress-default-cert
2023/07/23 18:28:30 Frontend HTTP listening on: 0.0.0.0:8080
2023/07/23 18:28:30 Frontend HTTPS listening on: 0.0.0.0:8443
2023/07/23 18:28:30 Controller sync period: 5s

2023/07/23 18:28:30 Running on haproxy-kubernetes-ingress-658f6845cd-cms84
2023/07/23 18:28:30 k8s/main.go:99 Running on Kubernetes version: v1.27.3 linux/amd64
2023/07/23 18:28:30 INFO    k8s/main.go:186 Global CR defined in API [core.haproxy.org/v1alpha2](http://core.haproxy.org/v1alpha2)
2023/07/23 18:28:30 INFO    k8s/main.go:186 Defaults CR defined in API [core.haproxy.org/v1alpha2](http://core.haproxy.org/v1alpha2)
2023/07/23 18:28:30 INFO    k8s/main.go:186 Backend CR defined in API [core.haproxy.org/v1alpha2](http://core.haproxy.org/v1alpha2)
2023/07/23 18:28:30 INFO    builder.go:243 running default backend server on :6061
2023/07/23 18:28:30 haproxy/main.go:100 Running with HAProxy version 2.7.9-7b77742 2023/06/07 - https://haproxy.org/
2023/07/23 18:28:36 INFO    monitor.go:119 Auxiliary HAProxy config '/etc/haproxy/haproxy-aux.cfg' updated
2023/07/23 18:28:36 ERROR   global.go:244 default service: service default-local-service: no service port matching '0'
2023/07/23 18:28:36 INFO    controller.go:161 HAProxy restarted
[NOTICE]   (212) : haproxy version is 2.7.9-7b77742
[WARNING]  (212) : Exiting Master process...
[ALERT]    (212) : Current worker (245) exited with code 143 (Terminated)
[WARNING]  (212) : All workers exited. Exiting... (0)
Memory limit for HAProxy: 3858MiB
[NOTICE]   (280) : New worker (287) forked
[NOTICE]   (280) : Loading success.
2023/07/23 18:28:41 ERROR   global.go:244 default service: service default-local-service: no service port matching ‘0'

I didn’t see this documented but assumed you needed a default-local-service, which I have created as follows and is running.  I attached details of it below.

Do you know what port 0 is referring to?

I also note the output after installation appears outdated.  It suggests the following yaml for Ingress.
  apiVersion: [networking.k8s.io/v1](http://networking.k8s.io/v1)
  kind: Ingress
  metadata:
    name: web-ingress
    namespace: default
    annotations:
      ingress.class: "haproxy"
  spec:
    rules:
    - host: [webdemo.com](http://webdemo.com/)
      http:
        paths:
        - path: /
          backend:
            serviceName: web
            servicePort: 80

I found this yaml format works, where above fails parsing:
apiVersion: [networking.k8s.io/v1](http://networking.k8s.io/v1)
kind: Ingress
metadata:
  name: nr-demo-mean-api-1-ing
  annotations:
    ingress.class: "haproxy"
spec:
  rules:
    - host: [nr-demo.com](http://nr-demo.com/)
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: nr-demo-mean-api-1-svc
                port:
                  number: 80

Port 0 should be specified below???

apiVersion: v1
kind: Service
metadata:
  name: default-local-service
  namespace: haproxy-controller
  labels:
    app: http-404-svc
spec:
  type: ClusterIP
  selector:
    app: http-404
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
—
kind: Deployment
metadata:
  name: http-404
  namespace: haproxy-controller
  labels:
    app: http-404
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-404
  template:
    metadata:
      labels:
        app: http-404
    spec:
      containers:
      - name: http-404
        image: [gcr.io/google_containers/defaultbackend:1.0](http://gcr.io/google_containers/defaultbackend:1.0)
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: "20Mi"
            cpu: "500m"

**Comment by nickpapadonis** [comment] 2023-07-23 19:56
I tried pulling latest from GitHub using the latest git helm repo and building the image.  Same error.

FYI
2023/07/23 19:53:13 HAProxy Ingress Controller v1.10.0 55ffe63.dev.dirty
2023/07/23 19:53:13 Build from: https://github.com/haproxytech/kubernetes-ingress
2023/07/23 19:53:13 Git commit date: 2023/06/26 20:01:15
2023/07/23 19:53:24 ERROR   global.go:249 default service: service default-local-service: no service port matching '0'

**Comment by NickMRamirez** [comment] 2023-07-24 13:44
@nickpapadonis I tried it and also get an error, but not the same one. I get this error:

```
ERROR   global.go:244 default service: service 'haproxy-controller/default-local-service' does not exist
```

The version installed is `HAProxy Ingress Controller v1.10.4 960be87.dirty`, same as you.

You should not need to install a default service yourself. In fact, prior to version 1.8, we had to specify a default service via the `--default-backend-service` startup flag, but after 1.8, the service is built in. Maybe this error is a side effect of that change. In any case, for me, although I get this error, the ingress controller still functions.

**Comment by ivanmatmati** [comment] 2023-07-24 14:04
@NickMRamirez The error message you see has normally no consequence. But anyway, a fix for this is about to be published.

**Comment by nickpapadonis** [comment] 2023-07-24 17:16
Ok.  I think part of my installation problems, using your CE instructions, was that I enabled Minikube 'ingress' addon.  This configures nginx as the ingress controller by default and perhaps causes problems.  I was also trying to have the Ingress service use a ClusterIP service controller IP, instead of a NodePort service controller.

**Comment by nickpapadonis** [comment] 2023-07-24 17:19
> In case it helps you (since you are running Minikube)... I run Minikube with Docker as the driver (rather than a VM). That makes the port mapping weird. This is how I run it to make it accessible at port 30000:
> 
> ```
> minikube start --driver=docker --ports=127.0.0.1:30000:30000
> helm install kubernetes-ingress haproxytech/kubernetes-ingress --create-namespace --namespace haproxy-controller --set controller.service.nodePorts.http=30000
> ```
> 
> Then I can access the service at http://localhost:30000/. For me, the default service is shown, which shows the message "Not Found".

Thanks I use the 'hyperkit' driver on Mac and also edited /etc/resolver/* per [https://minikube.sigs.k8s.io/docs/handbook/addons/ingress-dns/](url) so I can access Ingress 'host:' DNS are URLs path from my Mac, to simulate a a frontend/backend eliminating CORS problems.

**Comment by ivanmatmati** [comment] 2023-07-25 09:20
I'm looking at it. As @NickMRamirez , I can't reproduce the error message you've got. I've just remarked something. You have this in your logs:
`version 2.7.9-7b77742 2023/06/07`
Whereas  I've got :
`Running with HAProxy version 2.7.7-feedf14`
Did you do any change on your own ? Can you paste the output of:
`helm ls`

**Comment by ivanmatmati** [comment] 2023-08-22 12:08
No activity

**Closed by ivanmatmati** 2023-08-22 12:08 UTC
