### ISSUE TITLE
Controller doesn't recover from "Version mismatch"

### ISSUE THREAD

**Issue by joschg** [haproxytech/kubernetes-ingress#112] opened 2019-11-13 12:14 UTC
We're running the HAProxy ingress controller in our cluster on 28 pods and recently we started having some issues: some pods don't update their rules when we update ingresses. Restarting the pod fixes the problem. We digged into the logs and found the following:

controller-haproxy.go:158: 15: Version mismatch, transaction version: 84, configured version: 83
controller-monitor.go:121: 15: Version mismatch, transaction version: 84, configured version: 83

These lines appear every time the controller tries to update HAProxy's config: the update fails due to the version mismatch.
The issues happen sporadically and we don't know why exactly it happens. Still though, the controller is running and appears to be healthy from the outside but fails to update HAProxy's rules. Affected instances are stuck in this state and are not able to update until they are restarted.

To me this looks like a bug rather than expected behavior: the controller should either be able to deal with a version mismatch error (resyncing) or exit with an error if this error cannot be dealt with.

Kubernetes version: 1.13.1
HAProxy version: 2.0.6
HAProxy Ingress Controller version: 1.2.2

**Comment by oktalz** [comment] 2019-11-13 12:19
Hi @joschg 
This should definitely not happen, version is something used internally and should not have impact on how controller is used (it increases automatically on every update of HAProxy conf).
I will try to see what might be the cause.

**Comment by Mo3m3n** [comment] 2019-11-16 09:24
Hi @joschg
The controller version 1.2.2 is outdatd and a number of bugs are fixed in the dev branch.
Can you please try the dev tag and tell us if you still facing this issue ?
We are planning on making a new release 1.2.5 this Monday.

**Comment by joschg** [comment] 2019-11-18 16:33
Hi @Mo3m3n
Thanks for looking into this! We deployed 1.2.5 today and so far could not observe it happening again. We'll keep monitoring :)

**Comment by Mo3m3n** [comment] 2019-11-18 17:21
Cool, the version mismatch issue will automatically happen if you manually modify HAProxy configuration, however if this still gonna happen even when not editing HAProxy config then this is a confirmed bug.
Other than that, I agree with this "the controller should either be able to deal with a version mismatch error (resyncing) or exit with an error if this error cannot be dealt with", so let's keep this issue open until this is fixed.

**Closed** 2021-03-08 10:46 UTC
Labels: bug
