### ISSUE TITLE
Broken certificate should cause a warning, not a fatal error

### ISSUE THREAD

**Issue by EmielBruijntjes** [haproxytech/kubernetes-ingress#495] opened 2022-10-27 14:14 UTC
We ran into an issue when someone accidentally created a secret with a broken certificate. This caused a fatal error for haproxy. It would be more convenient to just generate a warning, the broken certificate to be ignored or skipped, and not to disrupt any of the other processing.
```
2022/10/27 13:09:03 ERROR   controller.go:145 unable to Sync HAProxy configuration !!
2022/10/27 13:09:03 ERROR   controller.go:146 14: err transactionId=926e4cbb-0000-4fde-be62-7ed798b1e842 
msg="config parsing [/etc/haproxy/haproxy.cfg.926e4cbb-0000-4fde-be62-7ed798b1e842:62] 'bind 0.0.0.0:443' unable to load certificate from file '/etc/haproxy/certs/frontend/server_example.pem'."
msg="config parsing [/etc/haproxy/haproxy.cfg.926e4cbb-0000-4fde-be62-7ed798b1e842:63] 'bind :::443' unable to load certificate from file '/etc/haproxy/certs/frontend/server_example.pem'."
msg="config Error(s) found in configuration file /etc/haproxy/haproxy.cfg.926e4cbb-0000-4fde-be62-7ed798b1e842"
msg="config Fatal errors found in configuration."
```

**Comment by dschuldt** [comment] 2022-11-01 07:22
Hi, mentioned it here https://github.com/haproxytech/kubernetes-ingress/issues/443

Best
D.

**Comment by oktalz** [comment] 2022-11-02 10:57
hi @EmielBruijntjes 

in fact, this is treated as an warning, because the previous configuration will still be working, controller won't exit with fatal error.

we can add this to a wish list for HAProxy itself to further improve user experience.

**Comment by EmielBruijntjes** [comment] 2022-12-13 08:22
@oktalz What happens if the pod crashes or is evicted from the node, or the entire node breaks down? In that case Kubernetes automatically assigns haproxy to a different node, doesn't it? Will haproxy then also use the "previous configuration"?

Anyway, we had a real issue in production with a broken certificate of a minor website that caused real downtime for other sites as well because haproxy did not start.

**Comment by ivanmatmati** [comment] 2022-12-13 08:43
Hi @EmielBruijntjes , a fresh pod creates its own configuration from scratch. If this one is faulty, HAProxy won't start. Configuration are not shared or kept in reference somewhere. The best protection from this kind of mistakes would be to run any configuration in staging or preproduction environment.

**Comment by EmielBruijntjes** [comment] 2022-12-13 10:52
Certificates are not always (I think: almost never) part of the static configuration, but are dynamically loaded by Haproxy when the secrets change. If Haproxy now picks up a broken certificate for whatever reason (a hickup in the automatic cert renewal process, a user who uploaded a broken cert, a cert authority that hands out a broken cert, etc, etc), it outputs a warning to stdout or stderr and keeps on running (which is good). But if the haproxy instance is evicted from the node and assigned to a different node, it refuses to start, even when all the other certs and settings are still fine (and this is not good).

This does not sound like a thing that is hard to solve, or is it?

**Comment by oktalz** [comment] 2022-12-13 14:51
@EmielBruijntjes yes, solution is quite easy as Ivan suggested, having preproduction environment to test what is pushed to production is best solution. Reading logs and reacting to warnings also helps.

There are many other ways how this can be solved, one of them being controller completely exiting on every user error (and this is user error, accidental or not), but that is not something we desire to do (even though it would be consistent then)

In any case, already running instances can handle this and 
if not otherwise, with reading logs this can be easily spotted and reacted before new instances are started.

We already know that crashing everything due to one mistake is not good, mistakes happen, 
other parts of setup is working and everything is safe.
However we an have an error, that error can be seen (either in logs or with traffic not being served as it should) and fixed easily.
And most importantly, any configuration error should be fixed and not just ignored.

We can try to think of a better solution and this will be considered, but its not as simple as one would think.
Its hard to say what is worse, running with broken certificate or ignoring certificate or completely failing.
One use case is worst case for someone else.

**Closed by oktalz** 2022-12-13 14:51 UTC
